### ISSUE TITLE
Ensure that the Ingress's Service is re-created and exists if it's deleted

### ISSUE THREAD

**Issue by julianvmodesto** [appscode/voyager#186]
If you delete the Service for your ingress e.g. with `kubectl delete service voyager-example`, then it's not created by the controller.

**Comment by TamalSaha** [comment]
@julianvmodesto , which version of Voyager are you using?

**Comment by TamalSaha** [comment]
This was addressed in https://github.com/appscode/voyager/pull/145

**Comment by TamalSaha** [comment]
@julianvmodesto , do you still see this issue with 1.5.6?

**Comment by julianvmodesto** [comment]
I believe so, but I'll verify one again to make sure

**Comment by sadlil** [comment]
The service should recreated if its deleted by hand.

**Comment by julianvmodesto** [comment]
Thanks @sadlil.

For some reason, I'm still seeing no service after running the deletion below. Should the recreation be immediate, or is there some delay time?

```
$ kubectl delete svc voyager-grafana
service "voyager-grafana" deleted
```

My Ingress definition
```
apiVersion: appscode.com/v1beta1
kind: Ingress
metadata:
  namespace: default
  name: grafana
  labels:
    app: grafana
  annotations:
    # Use the Voyager Ingress Controller
    kubernetes.io/ingress.class: voyager
spec:
  # Default backend
  backend:
    serviceName: grafana
    servicePort: 80
  loadBalancerSourceRanges:
...
```

Voyager version
```
$ kubectl exec --namespace=kube-system voyager-operator-1489841599-2vwkb /voyager version
Version = 1.5.6
VersionStrategy = tag
Os = linux
Arch = amd64
CommitHash = c7a6bb6a1435b949938f5e5e4034193d1dfb320b
GitBranch = release-1.5
GitTag = 1.5.6
CommitTimestamp = 2017-06-16T12:21:07
BuildTimestamp = 2017-06-16T12:23:35.026818
BuildHost = beast
BuildHostOs = linux
BuildHostArch = amd64
```

**Comment by julianvmodesto** [comment]
This works! It emits a panic -- i don't know if this is intended or not.

```
I0628 15:20:10.912931       1 watcher.go:225] DELETED/services required restore
E0628 15:20:10.913176       1 runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/root/go/src/github.com/appscode/voyager/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/root/go/src/github.com/appscode/voyager/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/root/go/src/github.com/appscode/voyager/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/go/src/runtime/asm_amd64.s:514
/usr/local/go/src/runtime/panic.go:489
/usr/local/go/src/runtime/panic.go:63
/usr/local/go/src/runtime/signal_unix.go:290
/root/go/src/github.com/appscode/voyager/pkg/watcher/watcher.go:272
/root/go/src/github.com/appscode/voyager/pkg/watcher/watcher.go:144
/root/go/src/github.com/appscode/voyager/pkg/watcher/watcher.go:381
/root/go/src/github.com/appscode/voyager/vendor/k8s.io/client-go/tools/cache/controller.go:206
<autogenerated>:56
/root/go/src/github.com/appscode/voyager/vendor/k8s.io/client-go/tools/cache/controller.go:342
/root/go/src/github.com/appscode/voyager/vendor/k8s.io/client-go/tools/cache/delta_fifo.go:451
/root/go/src/github.com/appscode/voyager/vendor/k8s.io/client-go/tools/cache/controller.go:147
/root/go/src/github.com/appscode/voyager/vendor/k8s.io/client-go/tools/cache/controller.go:121
/root/go/src/github.com/appscode/voyager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:96
/root/go/src/github.com/appscode/voyager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:97
/root/go/src/github.com/appscode/voyager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:52
/root/go/src/github.com/appscode/voyager/vendor/k8s.io/client-go/tools/cache/controller.go:121
/usr/local/go/src/runtime/asm_amd64.s:2197
E0628 15:20:10.913425       1 runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/root/go/src/github.com/appscode/voyager/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/root/go/src/github.com/appscode/voyager/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/root/go/src/github.com/appscode/voyager/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/go/src/runtime/asm_amd64.s:514
/usr/local/go/src/runtime/panic.go:489
/root/go/src/github.com/appscode/voyager/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58
/usr/local/go/src/runtime/asm_amd64.s:514
/usr/local/go/src/runtime/panic.go:489
/usr/local/go/src/runtime/panic.go:63
/usr/local/go/src/runtime/signal_unix.go:290
/root/go/src/github.com/appscode/voyager/pkg/watcher/watcher.go:272
/root/go/src/github.com/appscode/voyager/pkg/watcher/watcher.go:144
/root/go/src/github.com/appscode/voyager/pkg/watcher/watcher.go:381
/root/go/src/github.com/appscode/voyager/vendor/k8s.io/client-go/tools/cache/controller.go:206
<autogenerated>:56
/root/go/src/github.com/appscode/voyager/vendor/k8s.io/client-go/tools/cache/controller.go:342
/root/go/src/github.com/appscode/voyager/vendor/k8s.io/client-go/tools/cache/delta_fifo.go:451
/root/go/src/github.com/appscode/voyager/vendor/k8s.io/client-go/tools/cache/controller.go:147
/root/go/src/github.com/appscode/voyager/vendor/k8s.io/client-go/tools/cache/controller.go:121
/root/go/src/github.com/appscode/voyager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:96
/root/go/src/github.com/appscode/voyager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:97
/root/go/src/github.com/appscode/voyager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:52
/root/go/src/github.com/appscode/voyager/vendor/k8s.io/client-go/tools/cache/controller.go:121
/usr/local/go/src/runtime/asm_amd64.s:2197
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1a0e8e4]

goroutine 67 [running]:
github.com/appscode/voyager/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /root/go/src/github.com/appscode/voyager/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x126
panic(0x1c36de0, 0x2c58ef0)
        /usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/appscode/voyager/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /root/go/src/github.com/appscode/voyager/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x126
panic(0x1c36de0, 0x2c58ef0)
        /usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/appscode/voyager/pkg/watcher.(*Watcher).restoreResourceIfRequired(0xc42039ea00, 0xc42091b2c0)
        /root/go/src/github.com/appscode/voyager/pkg/watcher/watcher.go:272 +0xd64
github.com/appscode/voyager/pkg/watcher.(*Watcher).Dispatch(0xc42039ea00, 0xc42091b2c0, 0xc420786dc0, 0x1)
        /root/go/src/github.com/appscode/voyager/pkg/watcher/watcher.go:144 +0x85f
github.com/appscode/voyager/pkg/watcher.eventHandlerFuncs.func2(0x1e9eda0, 0xc420b3b0e0)
        /root/go/src/github.com/appscode/voyager/pkg/watcher/watcher.go:381 +0xab
github.com/appscode/voyager/vendor/k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnDelete(0xc4207b1630, 0xc4207b1650, 0xc4207b1640, 0x1e9eda0, 0xc420b3b0e0)
        /root/go/src/github.com/appscode/voyager/vendor/k8s.io/client-go/tools/cache/controller.go:206 +0x49
github.com/appscode/voyager/vendor/k8s.io/client-go/tools/cache.(*ResourceEventHandlerFuncs).OnDelete(0xc4207269a0, 0x1e9eda0, 0xc420b3b0e0)
        <autogenerated>:56 +0x73
github.com/appscode/voyager/vendor/k8s.io/client-go/tools/cache.NewIndexerInformer.func1(0x1c6ab00, 0xc420c714e0, 0x1c6ab00, 0xc420c714e0)
        /root/go/src/github.com/appscode/voyager/vendor/k8s.io/client-go/tools/cache/controller.go:342 +0x519
github.com/appscode/voyager/vendor/k8s.io/client-go/tools/cache.(*DeltaFIFO).Pop(0xc4202840c0, 0xc420773650, 0x0, 0x0, 0x0, 0x0)
        /root/go/src/github.com/appscode/voyager/vendor/k8s.io/client-go/tools/cache/delta_fifo.go:451 +0x27e
github.com/appscode/voyager/vendor/k8s.io/client-go/tools/cache.(*controller).processLoop(0xc4201f6480)
        /root/go/src/github.com/appscode/voyager/vendor/k8s.io/client-go/tools/cache/controller.go:147 +0x40
github.com/appscode/voyager/vendor/k8s.io/client-go/tools/cache.(*controller).(github.com/appscode/voyager/vendor/k8s.io/client-go/tools/cache.processLoop)-fm()
        /root/go/src/github.com/appscode/voyager/vendor/k8s.io/client-go/tools/cache/controller.go:121 +0x2a
github.com/appscode/voyager/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc42085bfb0)
        /root/go/src/github.com/appscode/voyager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:96 +0x5e
github.com/appscode/voyager/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc420e1bfb0, 0x3b9aca00, 0x0, 0x1b3fb01, 0xc420143380)
        /root/go/src/github.com/appscode/voyager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:97 +0xad
github.com/appscode/voyager/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc42085bfb0, 0x3b9aca00, 0xc420143380)
        /root/go/src/github.com/appscode/voyager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:52 +0x4d
github.com/appscode/voyager/vendor/k8s.io/client-go/tools/cache.(*controller).Run(0xc4201f6480, 0xc420143380)
        /root/go/src/github.com/appscode/voyager/vendor/k8s.io/client-go/tools/cache/controller.go:121 +0x237
created by github.com/appscode/voyager/pkg/watcher.(*Watcher).Service
        /root/go/src/github.com/appscode/voyager/pkg/watcher/objects.go:34 +0x29a


```

**Comment by tamalsaha** [comment]
Looks like an NPE. We are going to look into this.

**Comment by sadlil** [comment]
@julianvmodesto  #273 should fix this. If this problem still occurs let us know..

**Comment by julianvmodesto** [comment]
This looks good to me! :)
